---
title: "COVID-19 Variants Analysis"
output: html_notebook
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r, echo = FALSE, message=FALSE, warning=FALSE, comment=FALSE}
library(tidyverse)
library(scales)
library(plotly)
library(DT)
library(data.table)
library(gtable)
library(plotly)
library(lubridate)
library(vtable)
library(rjson)
library(timetk)
library(Rssa)
library(RColorBrewer)
library(gghighlight)
library(tseries)
library(forecast)
library(tsibble)
#library(brotools)

`%!in%` <- Negate(`%in%`)
```

```{r, echo = FALSE, warning=FALSE}
covid <- read_csv("data/owid-covid-data.csv",show_col_types = FALSE)
#variants <- read_csv("data/covid-variants.csv",show_col_types = FALSE)

gisaid <- as.data.frame(fread("data/gisaid_variants_statistics.tsv")) %>% 
  rename(date = `Week prior to`,
         count = `Submission Count`,
         perc_sequences = `% per Country and Week`,
         total = `Total per Country and Week`,
         variant = Value) %>% 
  mutate(date = ymd(date),
         perc_sequences = round(count / total * 100, 3))# %>% 
#  separate(variant, into = c("variant", "origin"), sep = c("first detected in "))

gisaid_variants <- gisaid %>% 
  filter(Type == "Variant") %>%
  separate(variant, c("variant", "origin"), sep = "first detected in ") %>% 
  select(-Type)
```

```{r}
covid_NAs <- covid %>% 
  group_by(location) %>% 
  summarise_all(funs(sum(is.na(.)))) %>% 
  pivot_longer(cols = -location, names_to = "Variable", values_to = "NAs") %>% 
  mutate(Percent = round(NAs / nrow(covid) * 100 ,2)) %>% 
  arrange(-NAs)
```

```{r}
st(covid)
```

```{r}
st(gisaid)
```



```{r}
covid_NAs %>% 
  group_by(location) %>% 
  summarise(total_pct_na = sum(Percent)) %>% 
  arrange(total_pct_na) %>% 
  kable(caption = "Percent of Missing Values by Location") %>% 
  kable_paper("striped", full_width = FALSE)
```

```{r}
#Helper function for filtering data
my_data <- function(country_covid_filter, country_gisaid_filter){
  data <- covid %>% 
    filter(location == country_covid_filter)
  gisaid_data <- gisaid_variants %>% 
    filter(Country == country_gisaid_filter)
  data <- left_join(data, gisaid_data, by = "date")
  data
}

#covid - United States
#gisaid - "USA"

us <- my_data("United States", "USA")
france <- my_data("France", "France")
germany <- my_data("Germany", "Germany")
skorea <- my_data("South Korea", "South Korea")
china <- my_data("China", "China")
austria <- my_data("Austria", "Austria")
```

```{r "US Plots"}
variants_plot <- ggplot(data = us, aes(x = date)) +
  geom_area(aes(y = perc_sequences, color = variant, fill = variant), position = "dodge", show.legend = FALSE) +
  theme_minimal()


cases_plot <-
  ggplot(data = us, aes(x = date)) +
  geom_line(aes(y = new_cases_per_million), show.legend = FALSE) +
  geom_line(aes(y = new_deaths_per_million)) + 
  theme_minimal()


deaths_plot <- ggplot(data = us, aes(x = date)) +
  geom_line(aes(y = new_deaths_per_million)) + 
  theme_minimal()


vaccinations_plot <- ggplot(us, aes(x = date)) +
  geom_line(aes(y = new_vaccinations_smoothed_per_million)) +
  theme_minimal()


variants_cases_plot <- ggplot(data = us, aes(x = date)) + 
  geom_area(aes(y = perc_sequences, color = variant, fill = variant), show.legend =FALSE, alpha = 0.5, position = "dodge") + 
  geom_line(aes(y = new_cases_smoothed_per_million / 40)) + 
  scale_y_continuous("Percent of Sequences", sec.axis=sec_axis(~.*40, name = "New Cases Per Million")) + 
  theme_minimal() + 
  labs(title = "Proportion of Covid Variants vs New Cases Per Million")  +
  annotate(geom="label", x=ymd(20210501), y=75, label="Alpha") +
  annotate(geom="label", x=ymd(20210901), y=75, label="Delta") +
  annotate(geom="label", x=ymd(20220201), y=75, label="Omicron") + 
  geom_vline(xintercept = ymd(20210101), linetype=2) +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available")


variants_deaths_plot <- ggplot(data = us, aes(x = date)) + 
  geom_area(aes(y = perc_sequences, color = variant, fill = variant),show.legend =FALSE, alpha = 0.5, position = "dodge") + 
  geom_line(aes(y = new_deaths_smoothed_per_million*5)) + 
  scale_y_continuous("Percent of Sequences", sec.axis=sec_axis(~./5, name = "New Deaths Per Million")) + 
  theme_minimal() + 
  labs(title = "Proportion of Covid Variants vs New Deaths Per Million - USA", x = "") +
  annotate(geom="label", x=ymd(20210501), y=50, label="Alpha") +
  annotate(geom="label", x=ymd(20210901), y=75, label="Delta") +
  annotate(geom="label", x=ymd(20220201), y=75, label="Omicron") + 
  geom_vline(xintercept = ymd(20210101), linetype=2) +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available")


cases_vaccinations_plot <- ggplot(data = us, aes(x = date)) +
  geom_line(aes(y = new_cases_smoothed_per_million), show.legend = FALSE) +
  geom_line(aes(y = people_vaccinated_per_hundred*50)) + 
  scale_y_continuous("New Cases Per Million", sec.axis=sec_axis(~./50, name = "People Vaccinated Per Hundred")) + 
  theme_minimal() + 
  labs(title = "New Cases Per Million vs. People Vaccinated Per Hundred - USA", x = "") + 
  geom_vline(xintercept = ymd(20210101), linetype=2) +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available")

deaths_vaccinations_plot <- ggplot(us, aes(x = date)) +
  geom_line(aes(y = new_deaths_per_million), show.legend = FALSE) +
  geom_line(aes(y = people_fully_vaccinated_per_hundred/7)) + 
  scale_y_continuous("New Deaths Per Million", sec.axis=sec_axis(~.*7, name = "People Vaccinated Per Hundred")) + 
  theme_minimal() + 
  labs(title = "New Deaths Per Million vs. People Fully Vaccinated Per Hundred - USA", x = "") + 
  geom_vline(xintercept = ymd(20210101), linetype=2) +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available")


variants_hospitalizations_plot <- ggplot(us, aes(x = date)) + 
  geom_area(aes(y = perc_sequences, color = variant, fill = variant), show.legend =FALSE, alpha = 0.5, position = "dodge") + 
  geom_line(aes(y = weekly_hosp_admissions_per_million / 5)) + 
  scale_y_continuous("Percent of Sequences", sec.axis=sec_axis(~.*5, name = "Hospitalizations Per Million")) + 
  theme_minimal() + 
  labs(title = "Proportion of Covid Variants vs Hospitalizations Per Million - USA", x = "") + 
  geom_vline(xintercept = ymd(20210101), linetype=2) +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available") +
  annotate(geom="label", x=ymd(20210501), y=50, label="Alpha") +
  annotate(geom="label", x=ymd(20210901), y=75, label="Delta") +
  annotate(geom="label", x=ymd(20220201), y=75, label="Omicron") + 
  geom_vline(xintercept = ymd(20210101), linetype=2) +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available")

variants_vaccinations_plot <- ggplot(us, aes(x = date)) + 
  geom_area(aes(y = perc_sequences, color = variant, fill = variant), show.legend =FALSE, alpha = 0.5, position = "dodge") + 
  geom_line(aes(y = people_fully_vaccinated_per_hundred)) + 
  scale_y_continuous("Percent of Sequences", sec.axis=sec_axis(~., name = "People Vaccinated Per Hundred")) + 
  theme_minimal() + 
  labs(title = "Proportion of Covid Variants vs People Fully Vaccinated - USA", x = "") +
  annotate(geom="label", x=ymd(20210501), y=50, label="Alpha") +
  annotate(geom="label", x=ymd(20210901), y=75, label="Delta") +
  annotate(geom="label", x=ymd(20220201), y=75, label="Omicron") + 
  geom_vline(xintercept = ymd(20210101), linetype=2) +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available")
```

```{r}
variants_vaccinations_plot
```

```{r}
variants_cases_plot <- ggplot(data = us, aes(x = date)) + 
  geom_area(aes(y = perc_sequences, color = variant, fill = variant), show.legend =FALSE, alpha = 0.5, position = "dodge") + 
  geom_line(aes(y = new_cases_smoothed_per_million / 40)) + 
  scale_y_continuous("Percent of Sequences", sec.axis=sec_axis(~.*40, name = "New Cases Per Million")) + 
  theme_minimal() + 
  labs(title = "Proportion of Covid Variants vs New Cases Per Million - USA", x = "") +
  annotate(geom="label", x=ymd(20210501), y=50, label="Alpha") +
  annotate(geom="label", x=ymd(20210901), y=75, label="Delta") +
  annotate(geom="label", x=ymd(20220215), y=75, label="Omicron")+ 
  geom_vline(xintercept = ymd(20210101), linetype=2, label = "Vaccines Publicly Available") +
  annotate(geom="label", x=ymd(20210101), y=25, label="Vaccines Publicly Available")

variants_cases_plot
```

```{r}
variants_hospitalizations_plot
```

```{r}
variants_deaths_plot
```

```{r}
library(ggplot2)
library(sf)
library(rnaturalearth)

world <- ne_countries(scale = "medium", returnclass = "sf", type = 'map_units')
class(world)

sf::sf_use_s2(FALSE)

europe_cropped <- st_crop(world, xmin = -20, xmax = 45,
                                    ymin = 30, ymax = 73)
ggplot() + geom_sf(data = europe_cropped) + theme_bw()
```

```{r}
world_variants_df <- gisaid_variants %>% 
    group_by(Country,) %>% 
    mutate(Country = case_when(
      Country == "USA" ~ "United States",
          TRUE ~ as.character(Country)
          )) %>% 
  summarise(most_recent_date = date[n()],
            prevalent_variant = variant[date == date[n()] & perc_sequences == max(perc_sequences[date == date[n()]])],
            .groups = 'drop') %>% 
  arrange(desc(most_recent_date)) %>% 
  rename(location = Country)

world_variants_df %>% 
  rename(Location = location,
         `Most Recent Date` = most_recent_date,
         `Prevalent Variant` = prevalent_variant) %>% 
  arrange(desc(`Most Recent Date`)) %>% 
  kable(caption = "Most Prevalent Variant by Location") %>% 
  kable_paper("striped", full_width = FALSE)
```

```{r, warning=FALSE}
world_cases_per_mil_df <- covid %>% 
  group_by(location) %>% 
  summarise(most_recent_date = date[max(which(!is.na(new_cases_smoothed_per_million)))],
              new_cases_per_mil = new_cases_smoothed_per_million[max(which(!is.na(new_cases_smoothed_per_million)))])

world_cases_df <- covid %>% 
  group_by(location) %>% 
  summarise(most_recent_date = date[max(which(!is.na(new_cases_smoothed)))],
              new_cases = new_cases_smoothed[max(which(!is.na(new_cases_smoothed)))])
```

```{r}
world_variants_loc <- left_join(world_variants_df, covid[, c("location", "iso_code")], by = "location", all.x = TRUE, all.y = FALSE) %>% 
  rename(gu_a3 = iso_code) %>% 
  unique()

world_cases_per_mil_loc <- left_join(world_cases_per_mil_df, covid[, c("location", "iso_code")], by = "location", all.x = TRUE, all.y = FALSE) %>% 
  rename(gu_a3 = iso_code) %>% 
  unique()

world_cases_loc <- left_join(world_cases_df, covid[, c("location", "iso_code")], by = "location", all.x = TRUE, all.y = FALSE) %>% 
  rename(gu_a3 = iso_code) %>% 
  unique()

world_variants_map <- left_join(world, world_variants_loc, by = "gu_a3", all.x = TRUE)

world_cases_per_mil_map <- left_join(world, world_cases_per_mil_loc, by = "gu_a3", all.x = TRUE)

world_cases_map <- left_join(world, world_cases_loc, by = "gu_a3", all.x = TRUE)
```

```{r}
ggplot(data = world_variants_map, aes(fill = prevalent_variant, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") + 
  labs(title = "Most Prevalent Covid Variant by Country") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "bottom", 
              legend.text= element_text(size = 6),
              legend.title = element_blank(),
              legend.key.size = unit(1, "line")
              ) 

ggplot(data = world_variants_map, aes(fill = prevalent_variant, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") + 
  labs(title = "Most Prevalent Covid Variant by Country - Europe") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 6),
              legend.title = element_blank(),
              legend.key.size = unit(1, "line")
              )  + 
  coord_sf(xlim = c(-20, 45), ylim = c(30, 73), expand = FALSE)

ggplot(data = world_variants_map, aes(fill = prevalent_variant, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") + 
  labs(title = "Most Prevalent Covid Variant by Country - Asia") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 6),
              legend.title = element_blank(),
              legend.key.size = unit(1, "line")
              )  + 
  coord_sf(xlim = c(50, 150), ylim = c(-20, 60), expand = FALSE)
```


```{r}
ggplot(data = world_cases_per_mil_map, aes(fill = new_cases_per_mil, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "New Cases Per Million") + 
  labs(title = "New Cases Per Million by Country") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "bottom", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_viridis_c(option = "F", direction = -1)

ggplot(data = world_cases_per_mil_map, aes(fill = new_cases_per_mil, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "New Cases Per Million") + 
  labs(title = "New Cases Per Million by Country - Europe") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_viridis_c(option = "F", direction = -1) +
     coord_sf(xlim = c(-20, 45), ylim = c(30, 73), expand = FALSE)

ggplot(data = world_cases_per_mil_map, aes(fill = new_cases_per_mil, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "New Cases Per Million") + 
  labs(title = "New Cases Per Million by Country - Asia") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_viridis_c(option = "F", direction = -1) + 
  coord_sf(xlim = c(50, 150), ylim = c(-20, 60), expand = FALSE)
```

```{r}
ggplot(data = world_cases_map, aes(fill = new_cases, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "New Cases") + 
  labs(title = "New Cases by Country") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "bottom", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_viridis_c(option = "F", direction = -1)

 ggplot(data = world_cases_map, aes(fill = new_cases, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "New Cases") + 
  labs(title = "New Cases by Country - Europe") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_viridis_c(option = "F", direction = -1) + 
  coord_sf(xlim = c(-20, 45), ylim = c(30, 73), expand = FALSE)


 ggplot(data = world_cases_map, aes(fill = new_cases, text = paste0("Country: ", name, "\nLast date: ", most_recent_date))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "New Cases") + 
  labs(title = "New Cases by Country - Asia") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_viridis_c(option = "F", direction = -1) + 
  coord_sf(xlim = c(50, 150), ylim = c(-20, 60), expand = FALSE)
```


```{r}
world_cases_per_mil_df %>% 
  filter(location %!in% c("World", "High income", "Europe", "European Union", "Asia", "Upper middle income", "Lower middle income", "Oceania", "North America", "South America")) %>% 
  rename(Location = location,
         `Most Recent Date` = most_recent_date,
         `New Cases Per Million` = new_cases_per_mil) %>% 
  arrange(-`New Cases Per Million`) %>% 
  kable(caption = "Most Recent Record of New Cases Per Million by Location") %>%
  kable_paper("striped", full_width = F)
```

```{r}
world_cases_df %>% 
  filter(location %!in% c("World", "High income", "Europe", "European Union", "Asia", "Upper middle income", "Lower middle income", "Oceania", "North America", "South America")) %>% 
  arrange(-new_cases) %>% 
  rename(Location = location,
         `Most Recent Date` = most_recent_date,
         `New Cases` = new_cases) %>% 
  kable(caption = "Most Recent Report of New Cases by Location") %>% 
  kable_paper("striped", full_width = F)
```

# Cluster Analysis

```{r}
#create cases set
cases <- covid %>% 
  filter(location %!in% c("World", "High income", "Europe", "European Union", "Asia", "Upper middle income", "Lower middle income", "Oceania", "North America", "South America", "Africa", "Low income")) %>% 
  select(date, location, new_cases_smoothed) %>%
  drop_na()

#spread data by cases
spread_cases <- cases %>% 
  select(date, location, new_cases_smoothed) %>% 
  drop_na %>% 
  spread(location, new_cases_smoothed)

#euclidean distance and ward's method
cases_t <- t(spread_cases[-1])
cases_dist <- dist(cases_t, method = "euclidean")
fit <- hclust(cases_dist, method = "ward.D")

#dendrogram
library(ggdendro)
ggdendrogram(fit, rotate = TRUE, theme_dendro = FALSE) +
  theme_minimal() + xlab("") + ylab("") + scale_y_continuous(labels = comma)

#create clusters
clustered_data <- cutree(fit, k = 5)
clustered_data_tidy <- as.data.frame(as.table(clustered_data)) %>% 
  glimpse()
colnames(clustered_data_tidy) <- c("location", "cluster")
clustered_data_tidy$location <- as.character(clustered_data_tidy$location)

#join clusters to location
joined_clusters <- cases %>% 
  inner_join(clustered_data_tidy, by = "location") %>% 
  glimpse()

#print table of clusters and counts
table(clustered_data_tidy$cluster)
```


```{r}
joined_clusters %>% 
  group_by(location) %>% 
  summarise(most_recent_date = date[max(which(!is.na(new_cases_smoothed)))],
            new_cases = new_cases_smoothed[max(which(!is.na(new_cases_smoothed)))],
            cluster = cluster[1]) %>% 
  merge(world_variants_df[, c("location", "prevalent_variant")], by = "location") %>% 
  arrange(-new_cases) %>% 
  rename(Location = location,
         `Most Recent Date` = most_recent_date,
         `New Cases` = new_cases,
         Cluster = cluster,
         `Prevalent Variant` = prevalent_variant) %>% 
  kable(caption = "Most Recent Report of New Cases, Cluster assignment, and Most Prevalent Variant by Location") %>% 
  kable_paper("striped", full_width = F)
```

```{r}
ggplot(joined_clusters) +
  geom_area(aes(x = date, y = new_cases_smoothed,fill = factor(cluster)), alpha = 0.5, position = "dodge") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) + 
  labs(title = "New Cases By Cluster", x = "", y = "", fill = "Cluster") 
```

```{r}
cluster1 <- joined_clusters %>% 
  filter(cluster == "1")

p <- ggplot(cluster1, aes(date, new_cases_smoothed)) +
  geom_line(aes(color = location)) +
  theme_minimal() +
  geom_smooth(method = "auto", color = "red", se = F, size = 0.5) +
  theme(legend.position = "none") +
 # facet_wrap(~location, scale = 'free') 
  labs(title = "Cluster 1")

p
```

```{r}
cluster2 <- joined_clusters %>% 
  filter(cluster == "2")

ggplot(cluster2, aes(date, new_cases_smoothed)) +
  geom_line(color = "grey") +
  theme_minimal() +
  geom_smooth(method = "auto", color = "red", se = F, size = 0.5) +
  facet_wrap(~location, scales = 'free') + 
  theme(axis.text.x = element_blank()) + 
  labs(title = "Cluster 2 New Cases Smoothed", x = "", y = "")+ 
  scale_y_continuous(labels = comma)
```

```{r}
cluster3 <- joined_clusters %>% 
  filter(cluster == "3")

ggplot(cluster3, aes(date, new_cases_smoothed)) +
  geom_line(color = "grey") +
  theme_minimal() +
  geom_smooth(method = "auto", color = "red", se = F, size = 0.5) +
  facet_wrap(~location, scales = 'free') + 
  theme(axis.text.x = element_blank(), axis.text.y = element_text(size = 6.5))+ 
  labs(title = "Cluster 3 New Cases Smoothed", y = "", x = "")+ 
  scale_y_continuous(labels = comma)
```

```{r}
cluster4 <- joined_clusters %>% 
  filter(cluster == "4")

ggplot(cluster4, aes(date, new_cases_smoothed)) +
  geom_line(color = "grey") +
  theme_minimal() +
  geom_smooth(method = "auto", color = "red", se = F, size = 0.5) +
  facet_wrap(~location, scale = 'free')+ 
  labs(title = "Cluster 4 New Cases Smoothed", y = "", x = "") + 
  scale_y_continuous(labels = comma)
```

```{r}
cluster5 <- joined_clusters %>% 
  filter(cluster == "5")

ggplot(cluster5, aes(date, new_cases_smoothed)) +
  geom_line(color = "grey") +
  theme_minimal() +
  geom_smooth(method = "auto", color = "red", se = F, size = 0.5) +
  facet_wrap(~location, scale = 'free')+ 
  labs(title = "Cluster 5 New Cases Smoothed", x = "", y = "") + 
  scale_y_continuous(labels = comma)
```

```{r}
#clustered_data_tidy %>% 
#  mutate(location = case_when(
#    location == "United States" ~ "United States"
#  ))

world_clusters_loc <- left_join(clustered_data_tidy, covid[, c("location", "iso_code")], by = "location", all.x = TRUE, all.y = FALSE) %>% 
  rename(gu_a3 = iso_code) %>% 
  unique()

world_clusters_map <- left_join(world, world_clusters_loc, by = "gu_a3", all.x = TRUE)
```

```{r}
ggplot(data = world_clusters_map, aes(fill = factor(cluster), text = paste0("Country: ", name, "\nCluster: ", cluster))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "Cluster") + 
  labs(title = "Countries Clustered by Cases Over Time") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "bottom", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_brewer(palette = "Accent")

ggplot(data = world_clusters_map, aes(fill = factor(cluster), text = paste0("Country: ", name, "\nCluster: ", cluster))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "Cluster") + 
  labs(title = "Countries Clustered by Cases Over Time - Europe") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_brewer(palette = "Accent") + 
         coord_sf(xlim = c(-20, 45), ylim = c(30, 73), expand = FALSE)


ggplot(data = world_clusters_map, aes(fill = factor(cluster), text = paste0("Country: ", name, "\nCluster: ", cluster))) + 
  geom_sf() + 
  xlab("") + 
  ylab("") +
  labs(fill = "Cluster") + 
  labs(title = "Countries Clustered by Cases Over Time - Asia") +
  theme(panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "white"),                legend.position = "right", 
              legend.text= element_text(size = 5),
              legend.key.size = unit(1, "line")
              ) + 
  scale_fill_brewer(palette = "Accent") + 
    coord_sf(xlim = c(50, 150), ylim = c(-20, 60), expand = FALSE)

```


```{r}
#export cases with clusters to csv for python analysis
#write.csv(joined_clusters, "data\\cases_clustered.csv")
```

# ARIMA modeling

```{r}
#USA
my_location <- "United States"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
summary(fit2)
summary(fit3)
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
#Cases vs Prevalent Variant
ggplot(data = us, aes(x = date)) + 
  geom_area(aes(y = perc_sequences, color = variant, fill = variant), show.legend =FALSE, alpha = 0.5, position = "dodge") + 
  geom_line(aes(y = new_cases_smoothed_per_million / 40)) + 
  scale_y_continuous("Percent of Sequences", sec.axis=sec_axis(~.*40, name = "New Cases Per Million")) + 
  theme_minimal() + 
  labs(title = paste(my_location, "- Proportion of Covid Variants vs New Cases Per Million"))  +
  annotate(geom="label", x=ymd(20210501), y=50, label="Alpha") +
  annotate(geom="label", x=ymd(20210901), y=75, label="Delta") +
  annotate(geom="label", x=ymd(20220215), y=75, label="Omicron")
```



```{r}
#Austria
my_location <- "Austria"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
#India
my_location <- "India"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
#France
my_location <- "France"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
france %>% 
  select(date, variant, perc_sequences) %>% 
  arrange(desc(date)) %>% 
  na.omit()
```


```{r}
#Germany
my_location <- "Germany"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
germany %>% 
  select(date, variant, perc_sequences) %>% 
  arrange(desc(date)) %>% 
  na.omit()
```


```{r}
#Italy
my_location <- "Italy"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
#South Korea
my_location <- "South Korea"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
skorea %>% 
  select(date, variant, perc_sequences) %>% 
  arrange(desc(date)) %>% 
  na.omit()
```


```{r}
#Vietnam
my_location <- "Vietnam"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
#China
my_location <- "China"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

```{r}
china %>% 
  select(date, variant, perc_sequences) %>% 
  arrange(desc(date)) %>% 
  na.omit()
```

```{r}
#Thailand

my_location <- "Thailand"

clean <- covid %>% 
filter(location == my_location) %>% 
select(date, new_cases_smoothed, new_deaths_smoothed, new_vaccinations_smoothed, new_cases_smoothed_per_million) %>% 
mutate(date = ymd(date))

fit <- auto.arima(clean[,c("new_cases_smoothed")])
fit2 <- auto.arima(clean[,c("new_deaths_smoothed")])
fit3 <- auto.arima(clean[,c("new_vaccinations_smoothed")])
fit4 <- auto.arima(clean[,c("new_cases_smoothed_per_million")])

summary(fit)
print("============================================")
summary(fit2)
print("============================================")
summary(fit3)
print("============================================")
summary(fit4)


forecastedValues <- forecast(fit, 30)
forecastedValues2 <- forecast(fit2, 30)
forecastedValues3 <- forecast(fit3, 30)
forecastedValues4 <- forecast(fit4, 30)

print(forecastedValues)
print(forecastedValues2)
print(forecastedValues3)
print(forecastedValues4)

clean$date[length(clean$date)]

clean %>% 
  mutate(num = seq(1,length(clean$date)))

seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30)

forecast <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues$mean, 
           Lo95 = forecastedValues$lower[,2],
           Hi95 = forecastedValues$upper[,2])

forecast2 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues2$mean, 
           Lo95 = forecastedValues2$lower[,2],
           Hi95 = forecastedValues2$upper[,2])

forecast3 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues3$mean, 
           Lo95 = forecastedValues3$lower[,2],
           Hi95 = forecastedValues3$upper[,2])

forecast4 <- data.frame(date = seq(clean$date[length(clean$date)] + 1, by = "days", length.out = 30), 
           pred = forecastedValues4$mean, 
           Lo95 = forecastedValues4$lower[,2],
           Hi95 = forecastedValues4$upper[,2])

#plot(forecastedValues)

#cases forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases"), x = "", y = "")

#cases per million
clean %>%
  ggplot() +
  geom_line(aes(y = new_cases_smoothed_per_million, x = date), colour = "black") +
  geom_ribbon(data = forecast4, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast4, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Cases Per Million"), x = "", y = "")

#Deaths forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_deaths_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast2, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast2, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Deaths"), x = "", y = "")

#Vaccines forecast
clean %>%
  ggplot() +
  geom_line(aes(y = new_vaccinations_smoothed, x = date), colour = "black") +
  geom_ribbon(data = forecast3, aes(x = date, ymin = Lo95, ymax = Hi95), fill = "gray", alpha = 0.5) +
  geom_line(data = forecast3, aes(x = date, y = pred), linetype = 2, colour = "red") + 
  theme_minimal() + 
  scale_y_continuous(labels = comma) +
  labs(title = paste(my_location, "30 Day Forecast of New Vaccinations"), x = "", y = "")
```

